# shutdown-ec2.yml

- name: Stop sandbox instances
  hosts:
    - webservers
    - loadbalancers
  become: true
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-02dd0f8a8a49d5e5f'
      - 'i-02dd0f8a8a49d5e5f'
      - 'i-02dd0f8a8a49d5e5f'
    region: us-east-2b
  tasks:
    - name: Stop the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
        vpc_subnet_id: subnet-19c9a963
        assign_public_ip: yes
